/*
  ==============================================================================

    license_data.h

    This file is auto generated by the license server

  ==============================================================================
*/

#pragma once

namespace licensing {
namespace Data {

const char* server      = "https://auth.example.com/";
const char* productPage = "https://github.com/ffAudio/LicenseServer/";
const char* productUuid = "abc-def-foo-bar";
const char* publicKey   = "foobar";
long        hash        = 123;
bool        closingPopupAllowed = true;

} // namespace Data
} // namespace licensing
